### ISSUE TITLE
exception occur when wrap the <Image> component from nextjs

### ISSUE THREAD

**Issue by catsky** [MinJieLiu/react-photo-view#136]
hi, the following code will raise a warning in nextjs project. could you please have a look? thanks
``` 
import Image from 'next/image';
...
<PhotoView src={url}>
    <Image
      src={url}
      alt="Uploaded Image"
      width={100}
      height={100}
      className={`w-10 h-10 ${displayClass}`}
    />
  </PhotoView>


```
**error info:**
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Q`.
    at Image (webpack-internal:///./node_modules/next/dist/client/image.js:27:22)
    at Q (webpack-internal:///./node_modules/react-photo-view/dist/react-photo-view.module.js:11:20787)
    at div
    at J (webpack-internal:///./node_modules/react-photo-view/dist/react-photo-view.module.js:11:19704)
    at div
    at div
    at div
    at ImageUploader (webpack-internal:///./components/ImageUploader.js:33:32)
    at div
    at div
    at div
    at div
    at div
    at div
    at div
    at form
    at ServiceForm (webpack-internal:///./components/services/Form.js:78:23)
    at Edit (webpack-internal:///./pages/cars/[id]/services/[sid]/edit.js:57:64)
    at div
    at div
    at div
    at MyApp (webpack-internal:///./pages/_app.js:30:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20742)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23635)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:70:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:216:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:407:27)
```

**Comment by MinJieLiu** [comment]
Custom components must be forwarded by the forwardRef

**Comment by huanlirui** [comment]
how to fix ?

**Comment by huanlirui** [comment]
> Custom components must be forwarded (向前) by the forwardRef

可以就这个报错代码 给个例子吗 大哥  
```
import Image from 'next/image';
...
<PhotoView src={url}>
    <Image
      src={url}
      alt="Uploaded Image"
      width={100}
      height={100}
      className={`w-10 h-10 ${displayClass}`}
    />
  </PhotoView>
```
