### ISSUE TITLE
最新版本的 create-react-app 無法安裝

### ISSUE THREAD

**Issue by King-May** [MinJieLiu/react-photo-view#54]
這款圖片檢視組件是我目前看過最好的，但使用最新版本 create-react-app 創建的專案無法安裝 react-photo-view

react：17.0.2
create-react-app：4.0.3

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-photo-view@0.5.2
npm ERR! node_modules/react-photo-view
npm ERR!   react-photo-view@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Administrator\AppData\Local\npm-cache\eresolve-report.txt for a full report.      

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2021-05-31T19_04_30_869Z-debug.log
```

```
0 verbose cli [
0 verbose cli   'E:\\IDE\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'i',
0 verbose cli   'react-photo-view'
0 verbose cli ]
1 info using npm@7.15.0
2 info using node@v16.2.0
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:D:\Users\Administrator\Downloads\my-app\.npmrc Completed in 1ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\Administrator\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\Administrator\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 8ms
20 timing npm:load:setTitle Completed in 1ms
21 timing npm:load:setupLog Completed in 0ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 15ms
26 timing config:load:flatten Completed in 3ms
27 timing arborist:ctor Completed in 1ms
28 timing idealTree:init Completed in 1047ms
29 timing idealTree:userRequests Completed in 3ms
30 silly idealTree buildDeps
31 silly fetch manifest react-photo-view@*
32 timing arborist:ctor Completed in 0ms
33 http fetch GET 304 https://registry.npmjs.org/react-photo-view 1908ms (from cache)
34 silly fetch manifest classnames@^2.2.0
35 http fetch GET 304 https://registry.npmjs.org/classnames 36ms (from cache)
36 silly fetch manifest react@^17.0.2
37 http fetch GET 304 https://registry.npmjs.org/react 32ms (from cache)
38 silly fetch manifest react@^16.8.0
39 timing idealTree Completed in 3043ms
40 timing command:install Completed in 3051ms
41 verbose stack Error: unable to resolve dependency tree
41 verbose stack     at Arborist.[failPeerConflict] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1210:25)
41 verbose stack     at Arborist.[loadPeerSet] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1177:34)
41 verbose stack     at async Arborist.[buildDepStep] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:880:11)
41 verbose stack     at async Arborist.buildIdealTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:218:7)
41 verbose stack     at async Promise.all (index 1)
41 verbose stack     at async Arborist.reify (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:136:5)
41 verbose stack     at async Install.install (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install.js:150:5)
42 verbose cwd D:\Users\Administrator\Downloads\my-app
43 verbose Windows_NT 10.0.19043
44 verbose argv "E:\\IDE\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "react-photo-view"
45 verbose node v16.2.0
46 verbose npm  v7.15.0
47 error code ERESOLVE
48 error ERESOLVE unable to resolve dependency tree
49 error
50 error While resolving: [1mmy-app[22m@[1m0.1.0[22m
50 error Found: [1mreact[22m@[1m17.0.2[22m[2m[22m
50 error [2mnode_modules/react[22m
50 error   [1mreact[22m@"[1m^17.0.2[22m" from the root project
50 error
50 error Could not resolve dependency:
50 error [35mpeer[39m [1mreact[22m@"[1m^16.8.0[22m" from [1mreact-photo-view[22m@[1m0.5.2[22m[2m[22m
50 error [2mnode_modules/react-photo-view[22m
50 error   [1mreact-photo-view[22m@"[1m*[22m" from the root project
50 error
50 error Fix the upstream dependency conflict, or retry
50 error this command with --force, or --legacy-peer-deps
50 error to accept an incorrect (and potentially broken) dependency resolution.
50 error
50 error See C:\Users\Administrator\AppData\Local\npm-cache\eresolve-report.txt for a full report.
51 verbose exit 1
```

**Comment by MinJieLiu** [comment]
```json
"peerDependencies": {
    "classnames": "^2.2.0",
    "react": ">=16.8.0",
    "react-dom": ">=16.8.0"
  },
```

0.5.3
